---
title: "Sniff and Normalize Place Names in R"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Normalize and Sniff Place Names in R}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=F}
library(tidyverse)
library(lubricity)
```

```{r test1}
# country name  cn    "United States"  country
# iso           cc2   "US"             country code
# iso3          cc3   "USA"            country code
# admin code 1  ac1   "US.VA"          state
# admin code 1  ac1n  "Virginia"       state
# admin code 2  ac2n  "US.VA.059"      county
# admin code 2  ac2n  "Fairfax County" county
countrify("US")
countrify("USA")
countrify("United States")
countrify("Vietnam")
countrify("Viet Nam")
codify.1("Virginia")
codify.2("Fairfax County")
codify.2("Fairfax Country")
```

```{r test2}
df.src <- 
  system.file("extdata", "feature.tsv", package = "lubricity") %>%
  read_tsv(col_types = cols(.default = "c"))
query <- sort(unique(df.src$country))

regx_list <- list(
  list(pattern = "(.+)", names = c("cn")),
  list(pattern = "(.+):\\s*(.+)", names = c("cn", "ac1")),
  # list(pattern = "(.+):\\s*(.+)", names = c("cn", "ac2")),
  list(pattern = "(.+):\\s*(.+),", names = c("cn", "ac1")),
  # list(pattern = "(.+):\\s*(.+),", names = c("cn", "ac2")),
  list(pattern = "(.+):\\s*.+,\\s*(.+)", names = c("cn", "ac1")),
  # list(pattern = "(.+):\\s*.+,\\s*(.+)", names = c("cn", "ac2")),
  list(pattern = "(.+):\\s*(.+)\\s*,\\s*(.+)", names = c("cn", "ac1", "ac2")),
  list(pattern = "(.+):\\s*(.+)\\s*,\\s*(.+)", names = c("cn", "ac2", "ac1"))
)

x <- distinct(df.src, country)

pull(x, country) %>%
  lapply(process_regx_list, regx_list = regx_list) %>%
  bind_rows() %>%
  bind_cols(x, .) %>%
  arrange(country)
```

```{r test3}
process_regx_list(
  "USA: Pittsburgh, Pennsylvania",
  regx_list = list(
    list(pattern = "(.+):\\s*.+,\\s*(.+)", names = c("cn", "ac1")),
    list(pattern = "(.+):\\s*(.+),", names = c("cn", "ac1")),
    list(pattern = "(.+):\\s*(.+),", names = c("cn", "ac2"))
  )
)
```
